CREATE PROCEDURE [dbo].[P_F_G_GET_SCOA_ITEM] (@chvFinYear INT, @chv1 VARCHAR = NULL, @chv2 VARCHAR = NULL)
AS
BEGIN
	SET NOCOUNT ON
	SELECT * FROM Item WHERE FINANCIAL_YEAR = @chvFinYear
	SET NOCOUNT OFF
END;