IF OBJECT_ID(N'P_F_G_GET_SCOA_ACCOUNT_BUDGET', N'P') IS NOT NULL DROP PROCEDURE [P_F_G_GET_SCOA_ACCOUNT_BUDGET];
IF OBJECT_ID (N'P_F_G_GET_SCOA_PROJECT', N'P') IS NOT NULL DROP PROCEDURE [P_F_G_GET_SCOA_PROJECT];
IF OBJECT_ID(N'P_F_G_GET_LEDGER_JOURNAL_SUMMARY', N'P') IS NOT NULL DROP PROCEDURE [P_F_G_GET_LEDGER_JOURNAL_SUMMARY];
IF OBJECT_ID (N'P_F_G_GET_LEDGER_JOURNAL_ERROR_LOG', N'P') IS NOT NULL DROP PROCEDURE [P_F_G_GET_LEDGER_JOURNAL_ERROR_LOG];
IF OBJECT_ID (N'P_F_G_UPD_LEDGER_JOURNAL', N'P') IS NOT NULL DROP PROCEDURE [P_F_G_UPD_LEDGER_JOURNAL];
IF OBJECT_ID (N'P_F_G_GET_SCOA_ITEM', N'P') IS NOT NULL DROP PROCEDURE [P_F_G_GET_SCOA_ITEM];
IF OBJECT_ID (N'P_F_G_GET_LEDGER_OPEN_PERIOD', N'P') IS NOT NULL DROP PROCEDURE [P_F_G_GET_LEDGER_OPEN_PERIOD]