CREATE PROCEDURE ExportSamrasSCOAMasterDataForBatch
  @batchId BIGINT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @collect TABLE ([T_SHORT_CODE] VARCHAR(40), [C_Transaction] VARCHAR(40), [C_Municipal demarcation code] VARCHAR(40), [C_UDPV_ACCOUNTING_GROUP] VARCHAR(40), [C_UDPV_CLASS] VARCHAR(40), [C_UDPV_SUB_CLASS] VARCHAR(40), [T_DESCRIPTION] VARCHAR(40), [C_USERID_doer] VARCHAR(40));
	INSERT INTO @collect ([T_SHORT_CODE], [C_Transaction], [C_Municipal demarcation code], [C_UDPV_ACCOUNTING_GROUP], [C_UDPV_CLASS], [C_UDPV_SUB_CLASS], [T_DESCRIPTION], [C_USERID_doer])
		SELECT
			DISTINCT affi.AccountingGroupID + '-' + affi.AssetCategoryID + '-' + affi.AssetSubCategoryID AS [T_SHORT_CODE],
			'NEW' AS C_Transaction,
			(select top 1 Value from AssetPolicyGeneral where Section = 'SCOA' and Identifier = 'MunicipalDemarcationCode') AS [C_Municipal demarcation code],
			(select top 1 ara.AccountingGroupName from AssetRefAccounting ara inner join AssetFinFormInput affi on affi.AccountingGroupID = ara.AccountingGroupID where affi.ComponentID = sj.ComponentID) AS [C_UDPV_ACCOUNTING_GROUP],
			(select top 1 arc.AssetCategoryName from AssetRefCategory arc inner join AssetFinFormInput affi on affi.AssetCategoryID = arc.AssetCategoryID where affi.ComponentID = sj.ComponentID) AS [C_UDPV_CLASS],
			(select top 1 arsc.AssetSubCategoryName from AssetRefSubCategory arsc inner join AssetFinFormInput affi on affi.AssetSubCategoryID = arsc.AssetSubCategoryID where affi.ComponentID = sj.ComponentID) AS [C_UDPV_SUB_CLASS],
			(select top 1 arsc.AssetSubCategoryName from AssetRefSubCategory arsc inner join AssetFinFormInput affi on affi.AssetSubCategoryID = arsc.AssetSubCategoryID where affi.ComponentID = sj.ComponentID) AS [T_DESCRIPTION],
			'IMQS Initial Take On' AS [C_USERID_doer]
		FROM
		  SCOAJournal sj
		INNER JOIN
		  AssetFinFormInput affi ON affi.ComponentID = sj.ComponentID
		WHERE
		  sj.IMQSBatchID = @batchId;
	select
		[@collect].C_Transaction,
		(select Value from AssetPolicyGeneral where Section = 'SCOA' and Identifier = 'MunicipalDemarcationCode') as [C_Municipal demarcation code],
		[T_SHORT_CODE],
		NULL as R_IDENTIFICATION_REFERENCE,
		[C_UDPV_ACCOUNTING_GROUP],
		[C_UDPV_CLASS],
		[C_UDPV_SUB_CLASS],
		NULL as C_UDPV_GROUP_TYPE,
		NULL as C_UDPV_TYPE,
		NULL as C_UDPV_COMPONENT_TYPE,
		NULL as C_UDPV_SUB_COMPONENT_TYPE,
		NULL as C_UDPV_GRAP,
		NULL as C_UDPV_GAMAP,
		NULL as C_UDPV_GFS,
		NULL as C_UDPV_HERITAGE_STATUS,
		[T_DESCRIPTION],
		NULL as T_MAKE,
		NULL as T_MODEL,
		NULL as T_MANUFACTURER_NUMBER,
		NULL as D_EFFECTIVE,
		NULL as D_PURCHASE,
		NULL as D_COMPLETION,
		NULL as D_DISPOSAL,
		NULL as C_UDPV_DISPOSAL_METHOD,
		NULL as T_EXTERNAL_SYS_ref_number,
		NULL as C_UDPV_SOURCE,
		[C_USERID_doer],
		NULL as A_ACQUIRED,
		NULL as A_DISPOSAL,
		NULL as C_UDPV_DISPOSAL_REASON,
		NULL as N_ERF_NUMERIC,
		NULL as C_UDPV_UTILISATION,
		NULL as C_UDPV_MUNICIPAL_SERVICE,
		NULL as C_UDPV_OWNED,
		NULL as T_TITLE_DEED,
		NULL as T_SURVEYOR_GENERAL_CODE,
		NULL as C_UDPV_DEPRECIATION_METHOD,
		NULL as C_UDPV_LOCATION,
		NULL as D_RESOLUTION_DECISION,
		NULL as R_EXTERNAL_REFERENCE_NUMBER,
		NULL as T_SCANNEDTAG_LOCATION,
		NULL as T_SCANNEDTAG_ITEM,
		NULL as N_USEFULLIFE_TERM,
		NULL as N_USEFULLIFE_YEARS,
		NULL as N_USEFULLIFE_MONTHS,
		NULL as N_USEFULLIFE_DAYS,
		NULL as N_TAKEON_USEFULLIFE_TERM,
		NULL as N_TAKEON_USEFULLIFE_YEARS,
		NULL as N_TAKEON_USEFULLIFE_MONTHS,
		NULL as N_TAKEON_USEFULLIFE_DAYS,
		NULL as N_TAKEON_AGE,
		NULL as T_SERIAL_NUMBER,
		NULL as D_RENEWAL,
		NULL as C_UDPV_RENEWAL_TYPE,
		NULL as C_UDPV_REVALUATION_METHOD,
		NULL as D_NEXT_REVALUATION,
		NULL as C_UDPV_UNIT_MEASURE,
		NULL as N_EXTENT_OF_ASSET,
		NULL as N_CAPACITY,
		NULL as C_UDPV_CRITICALITY,
		NULL as C_UDPV_CONDITION,
		NULL as C_UDPV_PERFORMANCE,
		NULL as C_UDPV_DATA_ACCURACY,
		NULL as T_GPS_LATITUDE_DECIMAL,
		NULL as T_GPS_LONGITUDE_DECIMAL,
		NULL as T_GPS_LATITUDE_DIRECTION,
		NULL as N_GPS_LATITUDE_DEGREE,
		NULL as N_GPS_LATITUDE_MINUTES,
		NULL as N_GPS_LATITUDE_SECONDS,
		NULL as T_GPS_LONGITUDE_DIRECTION,
		NULL as N_GPS_LONGITUDE_DEGREE,
		NULL as N_GPS_LONGITUDE_MINUTES,
		NULL as N_GPS_LONGITUDE_SECONDS,
		NULL as A_RESIDUAL,
		NULL as A_ANNUAL_DEPRECIATION,
		NULL as C_UDPV_TITLE_RESTRICTION_APPLI,
		NULL as C_UDPV_STATUS,
		NULL as D_RETIRED_FROM,
		NULL as D_HELD_FOR_DISPOSAL_FROM,
		NULL as P_UTILIZATION,
		NULL as C_UDPV_VALUATION_METHOD,
		NULL as N_DIMENSIONS,
		NULL as T_VEHICLE_REGISTRATION_NUMBER,
		NULL as T_VEHICLE_ENGINE_NUMBER,
		NULL as A_REPLACEMENT_COST,
		NULL as D_COMMISSIONING,
		NULL as D_DEPRECIATION,
		NULL as C_USERID_AUTH,
		NULL as C_UDPV_TYPE_OF_MAINTENANCE,
		NULL as C_UDPV_CATEGORY_OF_MAINTENANCE,
		NULL as T_Parent_SHORT_CODE
	from
		@collect;
END